#!/bin/bash

VERSION="0.1.2"

ENV_DIR="$HOME/.envman"

if [[ ! -d "$ENV_DIR" ]]; then
	mkdir -p "$ENV_DIR"
fi

## Util

Error() {
	if test "$#" -ne 1; then
		exit 255
	fi
	local err="$1"
	echo "Error: $err"
	echo "See -h for help"
	exit 1
}

Help() {
	# Display Help
	echo "Manage your environment with ease"
	echo "https://github.com/1vnt/envman"
	echo
	echo "Syntax: envman [-h|-V] <subcommand>"
	echo "Subcommands:"
	echo "  activate: Activate other environment"
	echo "  active: Print currently active environment"
	echo "  list: List available environments"
	echo "  new: Create new environment"
	echo "  edit: Edit environment with \$EDITOR"
	echo "  shell: Print command for executing the active env"
	echo "  help: Print this help text"
	echo "  version: Print short version info"
	echo
}

Version() {
	echo "Envman v$VERSION"
}

DoReloadEnv() {
	old="$ENV_DIR/.tmp"
	new="$ENV_DIR/active"
	
	for var in $(cat "$old"|grep export|awk '{sub(/=.*/,""); print $2}'); do
		echo "$var"
		unset "$var"
	done

	rm "$old"

	exec "$SHELL"
}

# usage: argc argreq
chk_argc() {
	if test "$1" -ne "$2"; then
		Error "Illegal number of parameters"
	fi
}

chk_file() {
	if [[ ! -f "$1" ]]; then
		echo "Error: File doesn't exist"
		exit 1
	fi
}

## COMMANDS
sub_activate() {
	chk_argc "$#" 1

	cp "$ENV_DIR/active" "$ENV_DIR/.tmp"
	local name="$1"
	local path="$ENV_DIR/$name.env"

	chk_file "$path"

	rm -f "$ENV_DIR/active"
	ln -s "$path" "$ENV_DIR/active"

	DoReloadEnv
}

sub_active() {
	chk_file "$ENV_DIR/active"

	local path="$(readlink -f "$ENV_DIR/active")"
	local base="$(basename "$path")"

	echo "Currently, '${base%.env}' is active"
}

sub_list() {
	echo "Available environments:"
	shopt -s globstar nullglob
	for file in "$ENV_DIR"/*.env; do
		base="$(basename "$file")"
		printf "\t%s\n" "${base%.env}"
	done
	exit
}

sub_shell() {
	echo "source $ENV_DIR/active"
}

sub_edit() {
	cp "$ENV_DIR/active" "$ENV_DIR/.tmp"
	local path=""
	local name="$1"
	if [ ! -z "$name" ]; then
		path="$ENV_DIR/$name.env"
	else
		path="$ENV_DIR/active"
	fi

	chk_file "$path"

	"$EDITOR" "$path"

	DoReloadEnv 
}

sub_new() {
	chk_argc "$#" 1

	local name="$1"
	local path="$ENV_DIR/$name.env"

	echo "Creating new environment '$name'"
	touch "$path"

	echo "Do you wish to edit the new environment?"

	select yn in "Yes" "No"; do
		case $yn in
		Yes)
			"$EDITOR" "$path"
			break
			;;
		No) exit 0 ;;
		esac
	done

	exit
}

sub_help() {
	Help
	exit
}

sub_version() {
	Version
	exit
}

## Main program
subcommand=$1

if [ -z "$subcommand" ]; then
	Help
	exit
fi

case $subcommand in
*)
	shift
	if [[ ! $(type -t "sub_${subcommand}") == function ]]; then
		Error "'$subcommand' is not a known subcommand."
	fi
	"sub_${subcommand}" $@
	;;
esac
